function editorField(key, title, original) {
  const value = state.activeRemix[key] || "";
  const limit = key === "script" ? 12000 : 4000;
  return `<section class="editor-field"><h3>${title}</h3><div class="${original === undefined ? "" : "translation-pair"}">${original === undefined ? "" : `<div><span class="copy-label">Оригинал</span><div class="original-text">${escapeHtml(original || "Нет исходного текста")}</div></div>`}<label><span class="copy-label">${original === undefined ? "Ваша редакция" : "Русская версия"}</span><textarea data-draft-field="${key}" data-autogrow rows="3" placeholder="Напишите свой текст" aria-label="${title}: ваша редакция" data-limit="${limit}">${escapeHtml(value)}</textarea></label></div></section>`;
}
function editorPage() {
  if (state.loadingEditor || !state.activeRemix) return shell(`<div class="page-state">${icon("circle-notch","spin")} Открываем редактор…</div>`);
  const r = state.activeRemix, source = r.source_reel;
  const textSource = source?.platform === "threads";
  document.title = `${r.title} | Hype Hunter`;
  const sourcePanel = source ? `<section class="source-panel"><h2>Оригинал</h2>${textSource ? "" : sourceLink(source,thumbnailMarkup(source,"editor-cover"))}<div class="source-byline">${sourceAvatar(source)}${sourceLink(source,`${escapeHtml(source.author)} ${icon("arrow-square-out")}`)}</div>${sourceLink(source,`<h3>${escapeHtml(source.title)}</h3>`)}<time class="muted">${formatAdded(source.published_at)}</time>${sourceMetrics(source)}${textSource ? `<div class="original-text">${escapeHtml(source.caption)}</div>` : `<details><summary>Описание</summary><p class="original-text">${escapeHtml(source.caption)}</p></details>`}${translationState(source)}${source.translation_status !== "completed" ? `<p class="form-help">Перевод пока недоступен. Можно работать с оригиналом и написать свою версию.</p>` : ""}</section>` : `<section class="source-panel"><h2>Ваша идея</h2><label class="field-label">О чём публикация?<textarea rows="8" data-draft-field="brief" data-autogrow data-limit="4000" placeholder="Сохраните здесь мысль, референс или заметки">${escapeHtml(r.brief)}</textarea></label><p class="form-help">Самостоятельный черновик без исходного материала.</p></section>`;
  return shell(`<nav class="breadcrumb"><a href="${escapeHtml(state.editorReturn || "/content-plan")}" data-route>${icon("arrow-left")} Назад</a><span>Remix</span></nav>
    <header class="editor-header"><div class="editor-title"><label class="visually-hidden" for="draft-title">Название публикации</label><textarea id="draft-title" class="title-input" data-draft-field="title" data-limit="255" data-autogrow rows="1">${escapeHtml(r.title)}</textarea><span data-save-status role="status" class="${state.saveError?"form-error":state.dirty?"muted":"save-success"}">${state.saveError || (state.dirty?"Есть несохранённые изменения":"Сохранено")}</span></div><div class="editor-header-actions"><button class="button secondary" data-action="save-remix">Сохранить</button><a class="button primary" href="${escapeHtml(planURL())}" data-route>${icon("calendar-blank")} В контент-план</a></div></header>
    <div class="editor-planning"><label>Формат<select data-editor-format><option value="reels" ${r.format==="reels"?"selected":""}>Reels</option><option value="threads" ${r.format==="threads"?"selected":""}>Threads</option></select></label><label>Статус${statusSelect(r)}</label>${r.status==="in_progress"?`<label>Этап<select data-editor-stage>${Object.entries(STAGES).filter(([key])=>r.format==="threads"?key==="text":key!=="text").map(([key,l])=>`<option value="${key}" ${r.production_stage===key?"selected":""}>${l}</option>`).join("")}</select></label>`:""}<label>Запланировано · Москва<input type="datetime-local" data-editor-date value="${dateInput(r.scheduled_at)}" /></label>${r.scheduled_at?`<button class="icon-button" data-action="clear-date" aria-label="Убрать дату">${icon("x")}</button>`:""}${r.status==="published"?`<span class="muted">Опубликовано: ${r.published_at?formatDateTime(r.published_at):"дата не указана"}</span>`:""}</div>
    <div class="editor-grid ${textSource ? "text-source-editor" : ""}">${sourcePanel}<section class="adaptation-panel"><header class="section-heading"><div><h2>${textSource?"Русская редакция":"Оригинал и русская версия"}</h2><p class="form-help">${textSource?"Оригинал слева. Доработайте русскую версию или подготовьте сценарий Reels.":"Оригинал сохраняется отдельно. Справа в каждой паре — ваш текст."}</p></div>${source?`<button class="button secondary compact" data-action="rewrite" aria-label="Вернуть исходный перевод">${icon("arrow-counter-clockwise")} Вернуть перевод</button>`:""}</header>${editorField("hook","Хук",textSource ? undefined : source?.original_hook)}${editorField("script",textSource?"Текст / сценарий":"Сценарий",textSource ? undefined : source?.original_script)}${editorField("cta","CTA",textSource ? undefined : source?.original_cta)}${textSource && r.format==="threads"?`<button class="button secondary" data-action="derive-reels">${icon("film-strip")} Создать отдельный сценарий Reels</button>`:""}</section>
    <section class="threads-panel"><div class="section-heading"><h2>Threads</h2>${icon("chats-circle")}</div><p class="form-help">Подготовьте публикацию из текущей редакции. Это не отправка в соцсеть.</p><label class="visually-hidden" for="thread-text">Текст Threads</label><textarea id="thread-text" data-draft-field="thread_text" data-limit="500" data-autogrow rows="10" placeholder="Ваш текст Threads">${escapeHtml(r.thread_text)}</textarea><span class="character-count ${Array.from(r.thread_text).length>500?"form-error":""}" data-character-count>${Array.from(r.thread_text).length}/500</span><button class="button primary" data-action="prepare-thread">${icon("text-align-left")} Подготовить для Threads</button><p class="form-help">Соберём хук, сценарий и CTA. Если текст длиннее 500 символов, подготовим фрагмент для дальнейшей редакции.</p>${r.format==="reels"?`<button class="button secondary" data-action="derive-threads">${icon("plus")} Отдельный черновик Threads</button>`:""}</section></div>`, "editor-page");
}
